from .video_processor import (
    NODE_CLASS_MAPPINGS as _VIDEO_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _VIDEO_DISPLAY,
    VideoProcessor,
)
from .image_processor import (
    NODE_CLASS_MAPPINGS as _EXAMPLE_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _EXAMPLE_DISPLAY,
    ImageProcessor,
)

NODE_CLASS_MAPPINGS = _VIDEO_CLASS | _EXAMPLE_CLASS
NODE_DISPLAY_NAME_MAPPINGS = _VIDEO_DISPLAY | _EXAMPLE_DISPLAY

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
